language: go

install:
  - export GOPATH=$HOME/quickdevel/statsamp
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
  - go get code.google.com/p/gcfg
  - go get code.google.com/p/go.text/transform
  - go get code.google.com/p/go.text/encoding/charmap

script:
  - cd $GOPATH
  - mkdir bin
  - go build -o bin/server statsamp/server
  - go build -o bin/updater statsamp/updater
