language: go

install:
  - export GOPATH=$HOME/build/quickdevel/statsamp
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
  - go get gopkg.in/gcfg.v1
  - go get golang.org/x/text/transform
  - go get golang.org/x/text/encoding/charmap

script:
  - cd $GOPATH
  - mkdir bin
  - go build -o bin/server statsamp/server
  - go build -o bin/updater statsamp/updater
